name: "PostgreSQL cluster"
description: " |
  PostgreSQL — an object-relational database (ORDBMS) master-replica cluster
"
version: "1.0"
category: "Databases"
maintainer: "EDW"
license: "GPLv3"
projectURL: https://github.com/eea/rancher-alarms/
