version: "2"
services:
  postgres:
    image: postgres:10.4
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${HOST_LABELS}
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
    - postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data:
    driver: local
