version: '2'
catalog:
  name: "Postgres"
  version: "1.0"
  description: "PostgreSQL"
  uuid: postgres-0
  minimum_rancher_version: "v1.2.0"
  questions:
  - variable: "HOST_LABELS"
    label: "Schedule Postgres MASTER service on hosts with the following host labels"
    description: "Comma separated list of host labels (e.g. key1=value1, key2=value2) to be used for scheduling"
    default: "db_master=yes"
    type: "string"
    required: true
  - variable: "POSTGRES_USER"
    description: "Postgres User"
    label: "Postgres User"
    required: true
    default: "postgres"
    type: "string"
  - variable: "POSTGRES_PASSWORD"
    description: "Postgres Password"
    label: "Postgres Password"
    required: true
    default: "postgres_password"
    type: "password"
  - variable: "TZ"
    label: "Time zone"
    description: "Time zone"
    default: "Europe/Bucharest"
    required: true
    type: "string"

services:
  postgres:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      initializing_timeout: 30000
      port: 5432
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate


