version: '2'
catalog:
    name: Elasticsearch
    version: 6.2.4-1.0
    description: Elasticsearch cluster
    uuid: elasticsearch-1

    questions:
        - variable: "cluster_name"
          type: "string"
          required: true
          label: "Cluster name"
          description: "Name of the Elasticsearch Cluster"
          default: "es-cluster"
        - variable: "host_labels"
          description: "Comma separated list of host labels (e.g. key1=value1, key2=value2) to be used for scheduling the services."
          label: "Schedule on hosts with following host labels"
          type: "string"
          required: true
          default: elastic=yes
        - variable: "ES_CLIENT_PORT"
          label: "ElasticSearch client exposed port"
          description: "Empty if you don't want the ES interface exposed on the server"
          type: "int"
        - variable: "CEREBRO_PORT"
          label: "Cerebro client exposed port"
          description: "Empty if you don't want the Cerebro web site exposed on the server"
          type: "int"
        - variable: "KIBANA_PORT"
          label: "Kibana client exposed port"
          description: "Empty if you don't want the Kibana web interface exposed on the server"
          type: "int"
        - variable: "master_heap_size"
          type: "string"
          required: true
          label: "Heap size (master nodes)"
          description: "Heap size to be allocated for Java (master nodes)"
          default: "512m"

        - variable: "master_mem_limit"
          type: "int"
          required: true
          label: "Memory limit in byte (master nodes)"
          description: "Memory limit in Byte per elasticsearch container. AT LEAST double the heap size! (master nodes)"
          default: 1073741824

        - variable: "data_heap_size"
          type: "string"
          required: true
          label: "Heap size (data nodes)"
          description: "Heap size to be allocated for Java (data nodes)"
          default: "512m"

        - variable: "data_mem_limit"
          type: "int"
          required: true
          label: "Memory limit in byte (data nodes)"
          description: "Memory limit in Byte per elasticsearch container. AT LEAST double the heap size! (data nodes)"
          default: 1073741824

        - variable: "client_heap_size"
          type: "string"
          required: true
          label: "Heap size (client nodes)"
          description: "Heap size to be allocated for Java (client nodes)"
          default: "512m"

        - variable: "client_mem_limit"
          type: "int"
          required: true
          label: "Memory limit in byte (client nodes)"
          description: "Memory limit in Byte per elasticsearch container. AT LEAST double the heap size! (client nodes)"
          default: 1073741824

        - variable: "minimum_master_nodes"
          type: "int"
          required: true
          label: "# of minimum Master Nodes"
          description: "Set the number of required master nodes to reach quorum. Sets initial scale to this value as well"
          default: 1

        - variable: "initial_data_nodes"
          type: "int"
          required: true
          label: "# of initial data nodes"
          description: "Set the initial number of data nodes"
          default: 2

        - variable: "initial_client_nodes"
          type: "int"
          required: true
          label: "# of initial client nodes"
          description: "Set the initial number of client nodes"
          default: 1
        - variable: "TZ"
          label: "Time zone"
          description: "Time zone"
          default: "Europe/Bucharest"
          required: true
          type: "string"
    
services:

  es-master:
    scale: ${minimum_master_nodes}

  es-worker:
    scale: ${initial_data_nodes}

  es-client:
    scale: ${initial_client_nodes}
  
  cluster-health:
    scale: 1
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      initializing_timeout: 60000
      port: 12345
      unhealthy_threshold: 3
      interval: 10000
      strategy: none



